const User = require('./user');
const Collaborate = require('./collaborate');
const Advertisement = require('./advertisement')
const Award = require('./award');
const Banner = require('./banner');
const Media = require('./media');
const FAQ = require('./faq');
const Partnership = require('./partnershipinfo');
const Advertisement = require('./advertisement');
module.exports = { User, Collaborate, Award, Banner, Media, FAQ, Partnership, Advertisement };